org.gradle.jvmargs=-Xmx4G


mod_name=What's your build
mod_id=whats_your_build
mod_license=MIT License
mod_group_id=me.clefal.whats_your_build
mod_authors=Clefal
mod_description=
mod_issue=https://github.com/TUsama/Whats-Your-Build/issues
deps.fabric_loader=0.16.10
deps.fzzy_config_version = 0.7.5
deps.lib_version=2.1.5
deps.common_networking=1.0.22

mod_version = 0.5.0