org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=5
org.gradle.parallel=true


mod_name=What's your build
mod_license=MIT License
mod_group_id=me.clefal.whats_your_build
mod_authors=Clefal
mod_description=
deps.fabric_loader=0.16.10
deps.fzzy_config_version = 0.7.0
deps.lib_version=2.0.17

mod_version = 0.4.3